application: lzyy-cai
version: cai-1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (.*~)|
 (.*\.py[co])|
 (\..*)|
 )$

builtins:
- datastore_admin: on
- deferred: on
- remote_api: on
 
inbound_services:
- warmup
- mail

default_expiration: "1d"

handlers:

#- url: /favicon\.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#  mime_type: image/x-icon

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /_ah/admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /_ah/info/.*
  script: $PYTHON_LIB/google/appengine/tools/dev_appserver_info
  login: admin

- url: /_ah/mail/write@.+\.appspotmail\.com
  script: admin.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: main.py

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html

  - error_code: timeout
    file: timeout.html
